In [1]:
import pandas as pd

ms1 = pd.read_csv("ms1.csv",encoding = "Big5")
ms1

    排名    怪物名稱 屬性
0    1      妮奧  水
1    2      千早  水
2    3     阿碧絲  暗
3    4   開膛手傑克  光
4    5      盧娜  暗
5    6     所羅門  光
6    7      亞森  暗
7    8      甘露  水
8    9      亞瑟  光
9   10     路西法  暗
10  11    聖德太子  火
11  12     琵莉卡  水
12  13      瑪娜  火
13  14    鬼丸國綱  火
14  15     惠比壽  火
15  16    風神雷神  水
16  17  惠比天少女組  木
17  18     蒙大拿  暗
18  19   安娜塔西亞  水
19  20     包青天  火